apiVersion: v1
kind: Service
metadata:
  labels:
    app: component-repository
  name: component-repository
  namespace: oih-dev-ns
spec:
  ports:
    - name: "1234"
      port: 1234
      protocol: TCP
      targetPort: 1234
  selector:
    app: component-repository
  type: NodePort
