kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: source-volume-claim
  namespace: oih-dev-ns
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
