apiVersion: v1
kind: Service
metadata:
  labels:
    app: meta-data-repository
  name: meta-data-repository
  namespace: oih-dev-ns
spec:
  type: NodePort
  selector:
      app: meta-data-repository
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
