apiVersion: apps/v1
kind: Deployment
metadata:
  name: meta-data-repository
  namespace: oih-dev-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meta-data-repository
  minReadySeconds: 10
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: meta-data-repository
    spec:
      containers:
        - name: meta-data-repository
          imagePullPolicy: IfNotPresent
          image: node:12-alpine
          workingDir: /usr/src/app/
          command: ["yarn"]
          args: ["watch-container"]
          env:
            - name: IAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: iamtoken
            - name: MONGODB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: metaDataMongourl
            - name: "INTROSPECT_TYPE"
              value: "basic"
            - name: RABBITMQ_URI
              value: amqp://guest:guest@rabbitmq-service.oih-dev-ns.svc.cluster.local:5672
            - name: "INTROSPECT_ENDPOINT_BASIC"
              value: "http://iam.oih-dev-ns.svc.cluster.local:3099/api/v1/tokens/introspect"
            - name: ORIGINWHITELIST
              value: "localoih.com,http://web-ui.localoih.com,http://localhost:3000"
            - name: PORT
              value: "3000"
            - name: API_BASE
              value: "/api/v1"
            - name: LOGGING_LEVEL
              value: info
            - name: DEBUG_MODE
              value: true
            - name: NODE_ENV
              value: development
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: code
              mountPath: /usr/src/app
              subPath: services/meta-data-repository
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 120
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "0.1"
              memory: 500Mi
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: source-volume-claim
