apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-directory
  name: app-directory
  namespace: oih-dev-ns
spec:
  type: NodePort
  selector:
    app: app-directory
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
