apiVersion: v1
kind: Service
metadata:
  labels:
    app: secret-service
  name: secret-service
  namespace: oih-dev-ns
spec:
  type: NodePort
  selector:
      app: secret-service
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
