apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-service
  namespace: oih-dev-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-service
  minReadySeconds: 10
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: secret-service
    spec:
      containers:
        - name: secret-service
          imagePullPolicy: IfNotPresent
          image: node:12-alpine
          workingDir: /usr/src/app
          command: ["yarn"]
          args: ["watch-container"]
          env:
            - name: NODE_ENV
              value: development
            - name: CRYPTO_DISABLED
              value: "true"
            - name: IAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: iamtoken
            - name: MONGODB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: secretServiceMongourl
            # - name: IAM_OIDC_SERVICE_CLIENT_ID
            #   value: 8ce00058-5f75-435f-9026-ad952480e15a
            # - name: IAM_OIDC_SERVICE_CLIENT_SECRET
            #   valueFrom:
            #     secretKeyRef:
            #       name: secret-service
            #       key: 'client-secret'
            - name: "INTROSPECT_TYPE"
              value: "basic"
            - name: "INTROSPECT_ENDPOINT_BASIC"
              value: "http://iam.oih-dev-ns.svc.cluster.local:3099/api/v1/tokens/introspect"
            - name: PORT
              value: "3000"
            - name: API_BASE
              value: "/api/v1"
            - name: LOGGING_LEVEL
              value: "info"
            - name: TTL_AUTHFLOW
              value: "2m"
            - name: DEBUG_MODE
              value: "true"
            - name: RABBITMQ_URI
              value: "amqp://guest:guest@rabbitmq-service.oih-dev-ns.svc.cluster.local:5672"
            - name: "ORIGINWHITELIST"
              value: "localoih.com,http://web-ui.localoih.com,http://localhost:3000"
          volumeMounts:
            - name: code
              mountPath: /usr/src/app
              subPath: services/secret-service
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 120
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "0.1"
              memory: 1000Mi
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: source-volume-claim
