kind: Deployment
apiVersion: apps/v1
metadata:
  name: attachment-storage-service
  namespace: oih-dev-ns
  labels:
    app: attachment-storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attachment-storage-service
  template:
    metadata:
      name: attachment-storage-service
      labels:
        app: attachment-storage-service
    spec:
      containers:
        - name: attachment-storage-service
          image: node:12-alpine #openintegrationhub/iam:latest #
          workingDir: /usr/src/app/
          command: ["yarn"]
          args: ["watch-container"]
          env:
            - name: REDIS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: REDIS_CONFIG
            - name: PORT
              value: '3002'
            - name: IAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: iamtoken
            - name: LOG_LEVEL
              value: trace
            - name: NODE_ENV
              value: development
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3002
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3002
          securityContext:
            privileged: false
          volumeMounts:
            - name: code
              mountPath: /usr/src/app
              subPath: services/attachment-storage-service
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: source-volume-claim
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
