apiVersion: v1
kind: Service
metadata:
  labels:
    app: audit-log
  name: audit-log
  namespace: oih-dev-ns
spec:
  type: NodePort
  selector:
      app: audit-log
  ports:
    - port: 3007
      targetPort: 3007
      protocol: TCP
