apiVersion: v1
kind: Service
metadata:
  labels:
    app: dispatcher-service
  name: dispatcher-service
  namespace: oih-dev-ns
spec:
  type: NodePort
  selector:
      app: dispatcher-service
  ports:
    - port: 3013
      targetPort: 3013
      protocol: TCP
